apiVersion: 1

datasources:
  - name: MQTT
    uid: mqtt
    type: grafana-mqtt-datasource
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      uri: tcp://mosquitto:1883
      clientID: grafana_lab
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsSkipVerify: false